spring.application.name=back_SuiviDrone
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_drone
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect